import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./(Home)/Navbar";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Footer from "./(Home)/Footer";

const inter = Outfit({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Online Exam Relief",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >  
        <Navbar />
        {children}
        <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
